

import type { Sport, Amenity, MembershipPlan, Facility, UserProfile, UserRole, UserStatus, FacilityOperatingHours, PricingModel, RentalEquipment } from './types';

// This file contains static mock data that is safe to be imported into client components.
// It has no server-side dependencies like the 'pg' database driver.

const sportsData: Sport[] = [
  { id: 'sport-1', name: 'Soccer', iconName: 'Goal' },
  { id: 'sport-2', name: 'Basketball', iconName: 'Dribbble' },
  { id: 'sport-3', name: 'Tennis', iconName: 'Activity' },
  { id: 'sport-4', name: 'Badminton', iconName: 'Feather' },
  { id: 'sport-5', name: 'Swimming', iconName: 'PersonStanding' },
  { id: 'sport-6', name: 'Yoga', iconName: 'Brain' },
  { id: 'sport-7', name: 'Cycling', iconName: 'Bike' },
  { id: 'sport-8', name: 'Dance', iconName: 'Music' },
  { id: 'sport-9', name: 'Camping', iconName: 'Tent' },
  { id: 'sport-10', name: 'Theatre', iconName: 'Drama' },
  { id: 'sport-13', name: 'Cricket', iconName: 'Dices' },
  { id: 'sport-14', name: 'Pool', iconName: 'Target' },
  { id: 'sport-15', name: 'PC Game/PS5', iconName: 'Gamepad2' },
  { id: 'sport-16', name: 'Gym', iconName: 'Dumbbell' },
];

export const mockSports: Sport[] = sportsData;

export function getMockSports(): Sport[] {
    return sportsData;
};


export const mockAmenities: Amenity[] = [
  { id: 'amenity-1', name: 'Parking', iconName: 'ParkingCircle' },
  { id: 'amenity-2', name: 'WiFi', iconName: 'Wifi' },
  { id: 'amenity-3', name: 'Showers', iconName: 'ShowerHead' },
  { id: 'amenity-4', name: 'Lockers', iconName: 'Lock' },
  { id: 'amenity-5', name: 'Equipment Rental', iconName: 'PackageSearch' },
  { id: 'amenity-6', name: 'Cafe', iconName: 'Utensils' },
  { id: 'amenity-7', name: 'Accessible', iconName: 'Users' },
];


export const mockStaticMembershipPlans: MembershipPlan[] = [
  { id: 'mem_basic_1', name: 'Basic', pricePerMonth: 0, benefits: ['Access to all facilities', 'Standard booking rates', 'Community access'] },
  { id: 'mem_premium_2', name: 'Premium', pricePerMonth: 999, benefits: ['10% off all bookings', 'Priority booking slots', 'Free equipment rental (2 items/month)', 'Access to exclusive events'] },
  { id: 'mem_pro_3', name: 'Pro', pricePerMonth: 2499, benefits: ['25% off all bookings', 'Unlimited priority booking', 'Unlimited free equipment rental', 'Free entry to all events', 'Personalized coaching tips (AI-powered)'] },
];

export function getStaticUsers(): UserProfile[] {
    return [
      { 
        id: 'user-admin-kunj', 
        name: 'Kunj Patel', 
        email: 'kunjp1157@gmail.com',
        password: 'Kunj@2810',
        role: 'Admin' as UserRole, 
        status: 'Active' as UserStatus,
        joinedAt: '2023-01-15T10:00:00Z', 
        loyaltyPoints: 1250, 
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/75.jpg', 
        dataAiHint: 'man smiling',
        isProfilePublic: true,
        achievements: [
            { id: 'achieve-1', name: 'First Booking', description: 'Made your first booking.', unlockedAt: '2023-01-20T10:00:00Z', iconName: 'Medal' },
            { id: 'achieve-2', name: 'Social Sharer', description: 'Shared an event on social media.', unlockedAt: '2023-02-10T10:00:00Z', iconName: 'Gift' },
            { id: 'achieve-3', name: 'Weekend Warrior', description: 'Booked on a Saturday and Sunday in the same week.', unlockedAt: '2023-03-05T10:00:00Z', iconName: 'Swords' },
            { id: 'achieve-4', name: 'Reviewer', description: 'Wrote your first review.', unlockedAt: '2023-03-15T10:00:00Z', iconName: 'MessageSquareText' },
        ],
        skillLevels: [
            { sportId: 'sport-1', sportName: 'Soccer', level: 'Intermediate' },
            { sportId: 'sport-3', sportName: 'Tennis', level: 'Beginner' },
        ],
        preferredSports: [
            getMockSports().find(s => s.id === 'sport-1')!,
            getMockSports().find(s => s.id === 'sport-3')!,
        ],
        teamIds: ['team-1'],
        membershipLevel: 'Premium',
      },
      { 
        id: 'user-owner-dana', 
        name: 'Dana White', 
        email: 'dana.white@example.com', 
        role: 'FacilityOwner' as UserRole, 
        status: 'Active' as UserStatus,
        joinedAt: '2023-02-20T11:30:00Z', 
        loyaltyPoints: 450, 
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/68.jpg', 
        dataAiHint: 'woman portrait',
        isProfilePublic: true,
        achievements: [],
        skillLevels: [],
        teamIds: [],
        membershipLevel: 'Basic',
      },
      {
        id: 'user-regular-charlie',
        name: 'Charlie Davis',
        email: 'charlie.davis@example.com',
        role: 'User' as UserRole,
        status: 'Active' as UserStatus,
        joinedAt: '2023-03-10T09:00:00Z',
        loyaltyPoints: 800,
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
        dataAiHint: 'man glasses',
        isProfilePublic: true,
         achievements: [
            { id: 'achieve-1', name: 'First Booking', description: 'Made your first booking.', unlockedAt: '2023-03-12T10:00:00Z', iconName: 'Medal' },
        ],
        skillLevels: [
            { sportId: 'sport-2', sportName: 'Basketball', level: 'Advanced' },
            { sportId: 'sport-13', name: 'Cricket', level: 'Intermediate' },
        ],
        preferredSports: [
            getMockSports().find(s => s.id === 'sport-2')!,
            getMockSports().find(s => s.id === 'sport-13')!,
        ],
        teamIds: ['team-1'],
        membershipLevel: 'Basic',
      },
      {
        id: 'user-new-user',
        name: 'Test User',
        email: 'user@gmail.com',
        password: 'user@123',
        role: 'User' as UserRole,
        status: 'Active' as UserStatus,
        joinedAt: '2024-01-01T12:00:00Z',
        loyaltyPoints: 50,
        profilePictureUrl: 'https://randomuser.me/api/portraits/lego/3.jpg',
        dataAiHint: 'lego avatar',
        isProfilePublic: true,
        achievements: [],
        skillLevels: [],
        preferredSports: [],
        teamIds: [],
        membershipLevel: 'Basic',
      },
      {
        id: 'user-new-owner',
        name: 'Test Owner',
        email: 'owner@gmail.com',
        password: 'owner@123',
        role: 'FacilityOwner' as UserRole,
        status: 'Active' as UserStatus,
        joinedAt: '2024-01-01T12:00:00Z',
        loyaltyPoints: 50,
        profilePictureUrl: 'https://randomuser.me/api/portraits/lego/4.jpg',
        dataAiHint: 'lego avatar',
        isProfilePublic: true,
        achievements: [],
        skillLevels: [],
        preferredSports: [],
        teamIds: [],
        membershipLevel: 'Basic',
      }
    ];
}

const defaultOperatingHours: FacilityOperatingHours[] = [
  { day: 'Mon', open: '08:00', close: '22:00' }, { day: 'Tue', open: '08:00', close: '22:00' },
  { day: 'Wed', open: '08:00', close: '22:00' }, { day: 'Thu', open: '08:00', close: '22:00' },
  { day: 'Fri', open: '08:00', close: '23:00' }, { day: 'Sat', open: '09:00', close: '23:00' },
  { day: 'Sun', open: '09:00', close: '20:00' },
];

const standardEquipment: RentalEquipment[] = [
    { id: 'equip-1', name: 'Soccer Ball', pricePerItem: 100, priceType: 'per_booking', stock: 20, sportIds: ['sport-1'] },
    { id: 'equip-2', name: 'Basketball', pricePerItem: 100, priceType: 'per_booking', stock: 15, sportIds: ['sport-2'] },
    { id: 'equip-3', name: 'Tennis Racket', pricePerItem: 250, priceType: 'per_hour', stock: 10, sportIds: ['sport-3'] },
    { id: 'equip-4', name: 'Tennis Balls (3)', pricePerItem: 50, priceType: 'per_booking', stock: 30, sportIds: ['sport-3'] },
    { id: 'equip-5', name: 'Badminton Racket', pricePerItem: 200, priceType: 'per_hour', stock: 12, sportIds: ['sport-4'] },
    { id: 'equip-6', name: 'Shuttlecock (tube)', pricePerItem: 150, priceType: 'per_booking', stock: 25, sportIds: ['sport-4'] },
    { id: 'equip-7', name: 'Cricket Bat', pricePerItem: 300, priceType: 'per_hour', stock: 8, sportIds: ['sport-13'] },
    { id: 'equip-8', name: 'Cricket Ball', pricePerItem: 150, priceType: 'per_booking', stock: 10, sportIds: ['sport-13'] },
    { id: 'equip-9', name: 'Yoga Mat', pricePerItem: 50, priceType: 'per_booking', stock: 20, sportIds: ['sport-6'] },
];

export function getStaticFacilities(): Facility[] {
    const allSports = getMockSports();
    return [
      {
        id: 'facility-1',
        name: 'Pune Sports Complex',
        type: 'Complex',
        address: '123 Stadium Way, Koregaon Park, Pune, 411001',
        city: 'Pune',
        location: 'Koregaon Park',
        description: 'A state-of-the-art multi-sport complex in the heart of the city. Perfect for professional training and casual play alike.',
        sports: [allSports.find(s => s.id === 'sport-1')!, allSports.find(s => s.id === 'sport-2')!],
        sportPrices: [
            { sportId: 'sport-1', price: 2500, pricingModel: 'per_hour_per_person' },
            { sportId: 'sport-2', price: 2200, pricingModel: 'per_hour_per_person' },
        ],
        amenities: [
          mockAmenities.find(a => a.id === 'amenity-1')!,
          mockAmenities.find(a => a.id === 'amenity-2')!,
          mockAmenities.find(a => a.id === 'amenity-3')!,
          mockAmenities.find(a => a.id === 'amenity-4')!,
          mockAmenities.find(a => a.id === 'amenity-6')!,
        ],
        operatingHours: defaultOperatingHours,
        rating: 4.8,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'soccer stadium',
        availableEquipment: standardEquipment.filter(e => e.sportIds.includes('sport-1') || e.sportIds.includes('sport-2')),
        ownerId: 'user-owner-dana',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-2',
        name: 'Deccan Gymkhana Tennis Club',
        type: 'Court',
        address: '456 Ace Avenue, Deccan, Pune, 411004',
        city: 'Pune',
        location: 'Deccan',
        description: 'Premier outdoor clay courts with a serene ambiance. Join our community of passionate tennis players.',
        sports: [allSports.find(s => s.id === 'sport-3')!],
        sportPrices: [ { sportId: 'sport-3', price: 1800, pricingModel: 'per_hour_flat' } ],
        amenities: [
          mockAmenities.find(a => a.id === 'amenity-1')!,
          mockAmenities.find(a => a.id === 'amenity-3')!,
          mockAmenities.find(a => a.id === 'amenity-4')!,
        ],
        operatingHours: defaultOperatingHours,
        rating: 4.5,
        isPopular: false,
        isIndoor: false,
        dataAiHint: 'tennis court',
        availableEquipment: standardEquipment.filter(e => e.sportIds.includes('sport-3')),
        maintenanceSchedules: [],
      },
      {
        id: 'facility-3',
        name: 'Kothrud Cricket Ground',
        type: 'Field',
        address: '789 Boundary Rd, Kothrud, Pune, 411038',
        city: 'Pune',
        location: 'Kothrud',
        description: 'A lush, expansive cricket field perfect for corporate matches and weekend games. Well-maintained pitch.',
        sports: [allSports.find(s => s.id === 'sport-13')!],
        sportPrices: [ { sportId: 'sport-13', price: 3000, pricingModel: 'per_hour_flat' } ],
        amenities: [
          mockAmenities.find(a => a.id === 'amenity-1')!,
          mockAmenities.find(a => a.id === 'amenity-6')!,
        ],
        operatingHours: defaultOperatingHours,
        rating: 4.7,
        isPopular: true,
        isIndoor: false,
        dataAiHint: 'cricket stadium',
        ownerId: 'user-owner-dana',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-4',
        name: 'The Aundh Swim & Gym Hub',
        type: 'Complex',
        address: '101 Fitness Lane, Aundh, Pune, 411007',
        city: 'Pune',
        location: 'Aundh',
        description: 'A complete fitness destination with an olympic-sized swimming pool and a fully-equipped modern gymnasium.',
        sports: [allSports.find(s => s.id === 'sport-5')!, allSports.find(s => s.id === 'sport-16')!],
        sportPrices: [
            { sportId: 'sport-5', price: 400, pricingModel: 'per_hour_per_person' },
            { sportId: 'sport-16', price: 500, pricingModel: 'per_hour_per_person' },
        ],
        amenities: [
          mockAmenities.find(a => a.id === 'amenity-1')!,
          mockAmenities.find(a => a.id === 'amenity-2')!,
          mockAmenities.find(a => a.id === 'amenity-3')!,
          mockAmenities.find(a => a.id === 'amenity-4')!,
          mockAmenities.find(a => a.id === 'amenity-6')!,
        ],
        operatingHours: defaultOperatingHours,
        rating: 4.9,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'swimming pool gym',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-5',
        name: 'Shuttle Up Badminton Arena',
        type: 'Court',
        address: '246 Shuttlecock Street, Baner, Pune, 411045',
        city: 'Pune',
        location: 'Baner',
        description: 'Indoor badminton arena with professional-grade courts and excellent lighting.',
        sports: [allSports.find(s => s.id === 'sport-4')!],
        sportPrices: [{ sportId: 'sport-4', price: 1200, pricingModel: 'per_hour_per_person' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-3')!],
        operatingHours: defaultOperatingHours,
        rating: 4.6,
        isPopular: false,
        isIndoor: true,
        dataAiHint: 'badminton court',
        availableEquipment: standardEquipment.filter(e => e.sportIds.includes('sport-4')),
        maintenanceSchedules: [],
      },
      {
        id: 'facility-6',
        name: 'Zenith Yoga & Dance Studio',
        type: 'Studio',
        address: '77 Harmony Plaza, Viman Nagar, Pune, 411014',
        city: 'Pune',
        location: 'Viman Nagar',
        description: 'A tranquil space for yoga, meditation, and various dance forms. Embrace your inner peace and rhythm.',
        sports: [allSports.find(s => s.id === 'sport-6')!, allSports.find(s => s.id === 'sport-8')!],
        sportPrices: [{ sportId: 'sport-6', price: 900, pricingModel: 'per_hour_per_person' }, { sportId: 'sport-8', price: 1100, pricingModel: 'per_hour_per_person' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-4')!, mockAmenities.find(a => a.id === 'amenity-3')!, mockAmenities.find(a => a.id === 'amenity-2')!],
        operatingHours: defaultOperatingHours,
        rating: 4.9,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'yoga studio',
        availableEquipment: standardEquipment.filter(e => e.sportIds.includes('sport-6')),
        maintenanceSchedules: [],
      },
      {
        id: 'facility-7',
        name: 'The Box Yard',
        type: 'Box Cricket',
        address: '88 Industrial Way, Hinjawadi, Pune, 411057',
        city: 'Pune',
        location: 'Hinjawadi',
        description: 'Fast-paced box cricket and futsal action. Perfect for a quick, high-energy game with friends.',
        sports: [allSports.find(s => s.id === 'sport-13')!, allSports.find(s => s.id === 'sport-1')!],
        sportPrices: [{ sportId: 'sport-13', price: 2000, pricingModel: 'per_hour_flat' }, { sportId: 'sport-1', price: 1800, pricingModel: 'per_hour_flat' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-5')!],
        operatingHours: defaultOperatingHours,
        rating: 4.4,
        isPopular: true,
        isIndoor: false,
        dataAiHint: 'box cricket',
        availableEquipment: standardEquipment.filter(e => e.sportIds.includes('sport-13') || e.sportIds.includes('sport-1')),
        maintenanceSchedules: [],
      },
      {
        id: 'facility-8',
        name: 'Nexus Gaming Lounge',
        type: 'Studio',
        address: '1 Tech Tower, Hinjawadi, Pune, 411057',
        city: 'Pune',
        location: 'Hinjawadi',
        description: 'High-end PC and console gaming lounge with the latest titles and fastest internet. Fuel your competitive spirit.',
        sports: [allSports.find(s => s.id === 'sport-15')!],
        sportPrices: [{ sportId: 'sport-15', price: 400, pricingModel: 'per_hour_per_person' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-2')!, mockAmenities.find(a => a.id === 'amenity-6')!],
        operatingHours: defaultOperatingHours,
        rating: 4.8,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'gaming lounge',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-9',
        name: 'Community Sports Hub',
        type: 'Complex',
        address: '55 Community Circle, Kothrud, Pune, 411038',
        city: 'Pune',
        location: 'Kothrud',
        description: 'A versatile community center offering a variety of sports for all ages, including cycling, pool, and more.',
        sports: [allSports.find(s => s.id === 'sport-7')!, allSports.find(s => s.id === 'sport-14')!, allSports.find(s => s.id === 'sport-10')!],
        sportPrices: [
            { sportId: 'sport-7', price: 500, pricingModel: 'per_hour_flat' },
            { sportId: 'sport-14', price: 600, pricingModel: 'per_hour_flat' },
            { sportId: 'sport-10', price: 400, pricingModel: 'per_hour_flat' },
        ],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-7')!],
        operatingHours: defaultOperatingHours,
        rating: 4.2,
        isPopular: false,
        isIndoor: false,
        dataAiHint: 'community center',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-10',
        name: 'Pune Super Master Arena',
        type: 'Complex',
        address: '1 Master Sports Rd, Central Pune, Pune, 411001',
        city: 'Pune',
        location: 'Central Pune',
        description: 'The ultimate destination for every sport imaginable. Our super master arena offers world-class facilities for a wide range of activities, ensuring an unparalleled experience for all athletes.',
        sports: allSports,
        sportPrices: allSports.map(sport => ({ sportId: sport.id, price: 1500, pricingModel: 'per_hour_per_person' })),
        amenities: mockAmenities,
        operatingHours: defaultOperatingHours,
        rating: 5.0,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'sports complex stadium',
        ownerId: 'user-owner-dana',
        maintenanceSchedules: [],
      },
      // --- NEW CITIES START HERE ---
      {
        id: 'facility-11',
        name: 'Mumbai Cricket Club',
        type: 'Field',
        address: '10 Marine Drive, Churchgate, Mumbai, 400020',
        city: 'Mumbai',
        location: 'Churchgate',
        description: 'Iconic cricket ground with breathtaking views of the Arabian Sea. Experience cricket at its finest.',
        sports: [allSports.find(s => s.id === 'sport-13')!],
        sportPrices: [{ sportId: 'sport-13', price: 4000, pricingModel: 'per_hour_flat' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-3')!, mockAmenities.find(a => a.id === 'amenity-4')!],
        operatingHours: defaultOperatingHours,
        rating: 4.9,
        isPopular: true,
        isIndoor: false,
        dataAiHint: 'mumbai cricket stadium',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-12',
        name: 'Bandra Soccer Arena',
        type: 'Field',
        address: '22 Carter Road, Bandra West, Mumbai, 400050',
        city: 'Mumbai',
        location: 'Bandra',
        description: 'A 5-a-side rooftop soccer turf offering a unique playing experience with panoramic city views.',
        sports: [allSports.find(s => s.id === 'sport-1')!],
        sportPrices: [{ sportId: 'sport-1', price: 3500, pricingModel: 'per_hour_flat' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-5')!, mockAmenities.find(a => a.id === 'amenity-6')!],
        operatingHours: defaultOperatingHours,
        rating: 4.7,
        isPopular: true,
        isIndoor: false,
        dataAiHint: 'rooftop soccer',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-13',
        name: 'Delhi Capital Courts',
        type: 'Complex',
        address: '5 Connaught Place, New Delhi, 110001',
        city: 'Delhi',
        location: 'Connaught Place',
        description: 'A modern indoor complex featuring professional basketball and badminton courts right in the city center.',
        sports: [allSports.find(s => s.id === 'sport-2')!, allSports.find(s => s.id === 'sport-4')!],
        sportPrices: [
            { sportId: 'sport-2', price: 2800, pricingModel: 'per_hour_per_person' },
            { sportId: 'sport-4', price: 1500, pricingModel: 'per_hour_per_person' },
        ],
        amenities: mockAmenities.slice(0, 5),
        operatingHours: defaultOperatingHours,
        rating: 4.6,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'indoor basketball court',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-14',
        name: 'Bangalore Tech Park Sports',
        type: 'Complex',
        address: '1 Electronic City, Bangalore, 560100',
        city: 'Bangalore',
        location: 'Electronic City',
        description: 'The perfect spot for tech professionals to unwind. Offers tennis, swimming, and a state-of-the-art gym.',
        sports: [allSports.find(s => s.id === 'sport-3')!, allSports.find(s => s.id === 'sport-5')!, allSports.find(s => s.id === 'sport-16')!],
        sportPrices: [
            { sportId: 'sport-3', price: 2000, pricingModel: 'per_hour_per_person' },
            { sportId: 'sport-5', price: 500, pricingModel: 'per_hour_per_person' },
            { sportId: 'sport-16', price: 600, pricingModel: 'per_hour_per_person' },
        ],
        amenities: mockAmenities,
        operatingHours: defaultOperatingHours,
        rating: 4.8,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'modern sports complex',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-15',
        name: 'Kolkata Eden Gardens Annex',
        type: 'Field',
        address: '1 Maidan, Kolkata, 700021',
        city: 'Kolkata',
        location: 'Maidan',
        description: 'Practice nets and fields adjacent to the legendary Eden Gardens. Perfect for aspiring cricketers.',
        sports: [allSports.find(s => s.id === 'sport-13')!],
        sportPrices: [{ sportId: 'sport-13', price: 2200, pricingModel: 'per_hour_flat' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!],
        operatingHours: defaultOperatingHours,
        rating: 4.5,
        isPopular: false,
        isIndoor: false,
        dataAiHint: 'cricket practice nets',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-16',
        name: 'Hyderabad Hi-Tech Badminton',
        type: 'Court',
        address: '50 HITEC City, Hyderabad, 500081',
        city: 'Hyderabad',
        location: 'HITEC City',
        description: 'World-class badminton courts with synthetic flooring, catering to both recreational and professional players.',
        sports: [allSports.find(s => s.id === 'sport-4')!],
        sportPrices: [{ sportId: 'sport-4', price: 1300, pricingModel: 'per_hour_per_person' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-4')!, mockAmenities.find(a => a.id === 'amenity-5')!],
        operatingHours: defaultOperatingHours,
        rating: 4.7,
        isPopular: true,
        isIndoor: true,
        dataAiHint: 'badminton arena',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-17',
        name: 'Chennai Marina Beach Sports',
        type: 'Field',
        address: '99 Marina Beach Road, Chennai, 600005',
        city: 'Chennai',
        location: 'Marina Beach',
        description: 'Enjoy a game of beach soccer with the sea breeze. A unique and refreshing playing experience.',
        sports: [allSports.find(s => s.id === 'sport-1')!],
        sportPrices: [{ sportId: 'sport-1', price: 1500, pricingModel: 'per_hour_flat' }],
        amenities: [mockAmenities.find(a => a.id === 'amenity-3')!],
        operatingHours: defaultOperatingHours,
        rating: 4.3,
        isPopular: false,
        isIndoor: false,
        dataAiHint: 'beach soccer',
        maintenanceSchedules: [],
      },
      {
        id: 'facility-18',
        name: 'Ahmedabad Riverfront Cycling',
        type: 'Complex',
        address: 'Sabarmati Riverfront, Ahmedabad, 380009',
        city: 'Ahmedabad',
        location: 'Sabarmati Riverfront',
        description: 'Dedicated cycling tracks and yoga spots along the scenic Sabarmati Riverfront.',
        sports: [allSports.find(s => s.id === 'sport-7')!, allSports.find(s => s.id === 'sport-6')!],
        sportPrices: [
            { sportId: 'sport-7', price: 300, pricingModel: 'per_hour_flat' },
            { sportId: 'sport-6', price: 800, pricingModel: 'per_hour_flat' },
        ],
        amenities: [mockAmenities.find(a => a.id === 'amenity-1')!, mockAmenities.find(a => a.id === 'amenity-6')!],
        operatingHours: defaultOperatingHours,
        rating: 4.6,
        isPopular: true,
        isIndoor: false,
        dataAiHint: 'riverfront park cycling',
        maintenanceSchedules: [],
      }
    ];
}
